export enum OrderStatus {
    RECIEVED = "RECIEVED",
    CREATED = "CREATED",
    IN_PRODUCTION = "IN_PRODUCTION",
    START_TO_DELIVERY = "START_TO_DELIVERY",
    DELIVERED = "DELIVERED",
    CANCELED = 'CANCELED'
}